version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/packages/cli'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/drill'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/falcon'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/huston'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/rover'
    schedule:
      interval: 'daily'
