version: "3.8"

services:
  mysql:
    image: mysql:8
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - asterism_network
  
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    networks:
      - asterism_network

networks:
  asterism_network:
    driver: bridge
