version: "3.8"

services:
  mysql:
    image: mysql:8
    platform: linux/x86_64
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - asterism_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=toor"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  postgres:
    image: postgres:15-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    networks:
      - asterism_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  asterism_network:
    driver: bridge
