name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  setup-dependencies:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: 'pnpm'
      - run: pnpm fetch

  package-tests:
    needs: setup-dependencies
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18, 20]
        package: [cli, drill, falcon, huston, rover]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: 'pnpm'
      - run: pnpm install
      - run: docker-compose up -d
      - name: Wait for databases to be healthy
        run: |
          while [ "$(docker-compose ps mysql | grep '(healthy)')" == "" ] || [ "$(docker-compose ps postgres | grep '(healthy)')" == "" ]; do
            echo "Waiting for databases to be healthy..."
            sleep 5
          done
      - run: cd packages/${{matrix.package}} && pnpm test
